{
	"version": 1593266192,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/playbutton-sheet0.png",
		"images/tiledbackground2.png",
		"images/off-sheet0.png",
		"images/on-sheet0.png",
		"images/câuhỏi-sheet0.png",
		"images/Đápán1-sheet0.png",
		"images/Đápán2-sheet0.png",
		"images/Đápán3-sheet0.png",
		"images/Đápánsai-sheet0.png",
		"images/heart-sheet0.png",
		"images/timer-sheet0.png",
		"images/star-sheet0.png",
		"images/tiledbackground3.png",
		"images/brokenheart-sheet0.png",
		"images/gamesymbol-sheet0.png",
		"images/gamesymbol2-sheet0.png",
		"images/gamesymbol3-sheet0.png",
		"images/gamesymbol4-sheet0.png",
		"images/gamesymbol5-sheet0.png",
		"images/scoreboard-sheet0.png",
		"images/newgamebutton-sheet0.png",
		"media/nhạc nền .m4a",
		"media/nhạc nền.ogg",
		"media/correct.m4a",
		"media/correct.ogg",
		"media/heartbreak.m4a",
		"media/heartbreak.ogg",
		"media/incorrect.m4a",
		"media/incorrect.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}